"""
Report Generator - Generate comprehensive bug bounty reports
"""

import json
import os
from datetime import datetime
from typing import Dict, List, Any
import base64

class ReportGenerator:
    def __init__(self, config_manager):
        self.config_manager = config_manager
        self.output_config = config_manager.get_output_config()
        self.reports_dir = self.output_config.get('reports_dir', 'reports')
        
        # Ensure reports directory exists
        os.makedirs(self.reports_dir, exist_ok=True)
    
    def generate_html_report(self, scan_data: Dict, filename: str = None) -> str:
        """Generate HTML report"""
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"bug_bounty_report_{timestamp}.html"
        
        filepath = os.path.join(self.reports_dir, filename)
        
        html_content = self._generate_html_content(scan_data)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return filepath
    
    def generate_json_report(self, scan_data: Dict, filename: str = None) -> str:
        """Generate JSON report"""
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"bug_bounty_report_{timestamp}.json"
        
        filepath = os.path.join(self.reports_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(scan_data, f, indent=2, default=str)
        
        return filepath
    
    def _generate_html_content(self, scan_data: Dict) -> str:
        """Generate HTML content for report"""
        vulnerabilities = scan_data.get('vulnerabilities', [])
        results = scan_data.get('results', [])
        scan_config = scan_data.get('scan_config', {})
        
        # Calculate statistics
        stats = self._calculate_statistics(vulnerabilities, results)
        
        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bug Bounty Report - {scan_config.get('target_url', 'Unknown Target')}</title>
    <style>
        {self._get_css_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header class="report-header">
            <h1>Bug Bounty Security Report</h1>
            <div class="report-info">
                <p><strong>Target:</strong> {scan_config.get('target_url', 'Unknown')}</p>
                <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                <p><strong>Scanner:</strong> Bug Bounty Hunter Pro v1.0</p>
            </div>
        </header>

        <section class="executive-summary">
            <h2>Executive Summary</h2>
            <div class="summary-stats">
                <div class="stat-card critical">
                    <h3>{stats['critical']}</h3>
                    <p>Critical</p>
                </div>
                <div class="stat-card high">
                    <h3>{stats['high']}</h3>
                    <p>High</p>
                </div>
                <div class="stat-card medium">
                    <h3>{stats['medium']}</h3>
                    <p>Medium</p>
                </div>
                <div class="stat-card low">
                    <h3>{stats['low']}</h3>
                    <p>Low</p>
                </div>
                <div class="stat-card info">
                    <h3>{stats['info']}</h3>
                    <p>Info</p>
                </div>
            </div>
            <p class="summary-text">
                This security assessment identified <strong>{len(vulnerabilities)}</strong> potential 
                security issues across the target application. The scan covered directory fuzzing, 
                subdomain enumeration, admin panel discovery, and JWT analysis.
            </p>
        </section>

        <section class="vulnerabilities">
            <h2>Vulnerabilities Found</h2>
            {self._generate_vulnerabilities_html(vulnerabilities)}
        </section>

        <section class="scan-results">
            <h2>Scan Results</h2>
            {self._generate_results_html(results)}
        </section>

        <section class="scan-configuration">
            <h2>Scan Configuration</h2>
            {self._generate_config_html(scan_config)}
        </section>

        <footer class="report-footer">
            <p>Generated by Bug Bounty Hunter Pro - Advanced Security Testing Platform</p>
            <p>Report generated on {datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}</p>
        </footer>
    </div>
</body>
</html>
        """
        
        return html
    
    def _calculate_statistics(self, vulnerabilities: List, results: List) -> Dict:
        """Calculate vulnerability statistics"""
        stats = {
            'critical': 0,
            'high': 0,
            'medium': 0,
            'low': 0,
            'info': 0,
            'total': len(vulnerabilities)
        }
        
        for vuln in vulnerabilities:
            severity = vuln.get('severity', '').lower()
            if severity in stats:
                stats[severity] += 1
        
        return stats
    
    def _generate_vulnerabilities_html(self, vulnerabilities: List) -> str:
        """Generate HTML for vulnerabilities section"""
        if not vulnerabilities:
            return "<p>No vulnerabilities found during the scan.</p>"
        
        html = "<div class='vulnerabilities-list'>"
        
        for i, vuln in enumerate(vulnerabilities, 1):
            severity = vuln.get('severity', 'Unknown').lower()
            severity_class = f"severity-{severity}"
            
            html += f"""
            <div class="vulnerability-item {severity_class}">
                <div class="vuln-header">
                    <h3>#{i} - {vuln.get('type', 'Unknown Vulnerability')}</h3>
                    <span class="severity-badge {severity_class}">{vuln.get('severity', 'Unknown')}</span>
                </div>
                <div class="vuln-details">
                    <p><strong>URL:</strong> <code>{vuln.get('url', 'N/A')}</code></p>
                    <p><strong>Description:</strong> {vuln.get('description', 'No description available')}</p>
                    <p><strong>Impact:</strong> {vuln.get('impact', 'No impact assessment available')}</p>
                    {self._generate_vuln_extra_info(vuln)}
                </div>
            </div>
            """
        
        html += "</div>"
        return html
    
    def _generate_vuln_extra_info(self, vuln: Dict) -> str:
        """Generate extra vulnerability information"""
        extra_html = ""
        
        # Add JWT-specific information
        if 'secret' in vuln:
            extra_html += f"<p><strong>Weak Secret:</strong> <code>{vuln['secret']}</code></p>"
        
        # Add remediation if available
        if 'remediation' in vuln:
            extra_html += f"<p><strong>Remediation:</strong> {vuln['remediation']}</p>"
        
        return extra_html
    
    def _generate_results_html(self, results: List) -> str:
        """Generate HTML for scan results section"""
        if not results:
            return "<p>No scan results available.</p>"
        
        html = """
        <table class="results-table">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>URL/Endpoint</th>
                    <th>Status</th>
                    <th>Details</th>
                </tr>
            </thead>
            <tbody>
        """
        
        for result in results:
            html += f"""
            <tr>
                <td>{result.get('type', 'Unknown')}</td>
                <td><code>{result.get('url', 'N/A')}</code></td>
                <td>{result.get('status', 'Unknown')}</td>
                <td>{result.get('details', 'No details')}</td>
            </tr>
            """
        
        html += """
            </tbody>
        </table>
        """
        
        return html
    
    def _generate_config_html(self, scan_config: Dict) -> str:
        """Generate HTML for scan configuration section"""
        html = """
        <table class="config-table">
            <tbody>
        """
        
        config_items = [
            ('Target URL', scan_config.get('target_url', 'N/A')),
            ('Threads', scan_config.get('threads', 'N/A')),
            ('Timeout', f"{scan_config.get('timeout', 'N/A')} seconds"),
            ('Directory Scan', 'Yes' if scan_config.get('directory_scan') else 'No'),
            ('Subdomain Scan', 'Yes' if scan_config.get('subdomain_scan') else 'No'),
            ('JWT Analysis', 'Yes' if scan_config.get('jwt_analysis') else 'No'),
            ('Admin Panel Discovery', 'Yes' if scan_config.get('admin_panel') else 'No'),
            ('Bypass Redirects', 'Yes' if scan_config.get('bypass_redirects') else 'No'),
            ('Wordlist', scan_config.get('wordlist', 'N/A'))
        ]
        
        for key, value in config_items:
            html += f"""
            <tr>
                <td><strong>{key}</strong></td>
                <td>{value}</td>
            </tr>
            """
        
        html += """
            </tbody>
        </table>
        """
        
        return html
    
    def _get_css_styles(self) -> str:
        """Get CSS styles for the HTML report"""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }

        .report-header {
            text-align: center;
            margin-bottom: 30px;
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border-radius: 8px;
        }

        .report-header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }

        .report-info p {
            margin: 5px 0;
            font-size: 1.1em;
        }

        .executive-summary {
            margin-bottom: 30px;
        }

        .summary-stats {
            display: flex;
            justify-content: space-around;
            margin: 20px 0;
            flex-wrap: wrap;
        }

        .stat-card {
            text-align: center;
            padding: 20px;
            border-radius: 8px;
            color: white;
            min-width: 120px;
            margin: 5px;
        }

        .stat-card.critical { background-color: #d32f2f; }
        .stat-card.high { background-color: #f57c00; }
        .stat-card.medium { background-color: #fbc02d; }
        .stat-card.low { background-color: #388e3c; }
        .stat-card.info { background-color: #1976d2; }

        .stat-card h3 {
            font-size: 2em;
            margin-bottom: 5px;
        }

        .summary-text {
            background-color: #f8f9fa;
            padding: 15px;
            border-left: 4px solid #007bff;
            margin-top: 20px;
        }

        h2 {
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
            margin: 30px 0 20px 0;
        }

        .vulnerabilities-list {
            margin-top: 20px;
        }

        .vulnerability-item {
            margin-bottom: 20px;
            border: 1px solid #ddd;
            border-radius: 8px;
            overflow: hidden;
        }

        .vuln-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 15px;
            background-color: #f8f9fa;
        }

        .vuln-header h3 {
            margin: 0;
            color: #2c3e50;
        }

        .severity-badge {
            padding: 5px 10px;
            border-radius: 20px;
            color: white;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 0.8em;
        }

        .severity-badge.severity-critical { background-color: #d32f2f; }
        .severity-badge.severity-high { background-color: #f57c00; }
        .severity-badge.severity-medium { background-color: #fbc02d; color: #333; }
        .severity-badge.severity-low { background-color: #388e3c; }
        .severity-badge.severity-info { background-color: #1976d2; }

        .vuln-details {
            padding: 15px;
        }

        .vuln-details p {
            margin-bottom: 10px;
        }

        code {
            background-color: #f4f4f4;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: 'Courier New', monospace;
            color: #d63384;
        }

        .results-table, .config-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        .results-table th,
        .results-table td,
        .config-table td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        .results-table th {
            background-color: #f8f9fa;
            font-weight: bold;
            color: #2c3e50;
        }

        .results-table tr:hover {
            background-color: #f5f5f5;
        }

        .report-footer {
            margin-top: 40px;
            padding: 20px;
            text-align: center;
            background-color: #f8f9fa;
            border-top: 1px solid #ddd;
            color: #666;
        }

        @media (max-width: 768px) {
            .summary-stats {
                flex-direction: column;
                align-items: center;
            }
            
            .vuln-header {
                flex-direction: column;
                align-items: flex-start;
            }
            
            .vuln-header h3 {
                margin-bottom: 10px;
            }
        }
        """